### PR TITLE
Narrow feature completion list and provide quick fix for invalid feature

### PR DESCRIPTION
**Pull request by cherylking**
Related to #180

### CODE REVIEW

**Comment by cherylking** [comment]
This is what the quick fix looks like:

Screenshot 2023-09-08 at 1 39 25 PM

Screenshot 2023-09-08 at 1 39 10 PM

**Review by dshimo — APPROVED** [review]
Would this be merged into `main` as a completion list fix or `4q2023` with the addition of a new quick fix feature? Looks good to me either way.

**Review by evie-lau — APPROVED** [review]

**Comment by cherylking** [comment]
> Would this be merged into `main` as a completion list fix or `4q2023` with the addition of a new quick fix feature? Looks good to me either way.

@dshimo  Good point. Originally I was just trying to fix the completion list. But this is more of an enhancement that should probably be targeted to `4q2023`. Is it easy to change the PR to target a different branch? Or do I need to close this one and open a new one?

**Comment by dshimo** [comment]
@cherylking Seems like you got it. We're good to merge

**Pull request merged**
